#!/usr/bin/env bash

echo stm32u5g9 run script

COMMAND=$1
CONFIG_PATH=$2
BOARD_NAME=$3
CONFIG_NAME=$4
SOCKET_PATH=$5

echo "COMMAND=$COMMAND CONFIG_PATH=$CONFIG_PATH BOARD_NAME=$BOARD_NAME CONFIG_NAME=$CONFIG_NAME SOCKET_PATH=$SOCKET_PATH"
